### ISSUE TITLE
Math functions in JavaScript

### ISSUE THREAD

**Issue by sairohith2605** [AVNIETTech/javascript-dev#2]
Exercise the math functions in JavaScript.

**Comment by sairohith2605** [comment]
@Datta973 or @bvgraghu1298, could you please review the code in the master branch? 
Let's keep the thread in case of an issue, or let's close it once the review is over.

**Comment by Datta973** [comment]
okay, everything seems fine, the only issue is tab spacing.
Some places tabs spaces are too many 
Solution : Just align all of the text towards left ,without any tab spaces

**Comment by pskiran8055** [comment]
Ok

**Comment by pskiran8055** [comment]
> okay, everything seems fine, the only issue is tab spacing.
> Some places tabs spaces are too many 
> Solution : Just align all of the text towards left ,without any tab spaces

Ok

**Comment by Datta973** [comment]
great work nonetheless :smile: :smile: :+1:

**Comment by sairohith2605** [comment]
Yup, it's a good work though! Heading towards a great start. 

Continuing in a new issue, #3 and closing this.
